### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by STRd6** [farskipper/ecmaless#1]
Hey, I really like your description of the project goals, but I can't find any docs or examples showcasing the language.

Thanks!

**Comment by farskipper** [comment]
Glad you found it and find it interesting. You can’t find docs or examples because they’re not there :) I wrote up some notes back when I was starting this, I’ll push them into the README.

**Comment by farskipper** [comment]
Ok, it's been updated.

If this is something you are interested in working on I'd be happy to help you get setup! However, as noted in the readme, I'm not currently working on it.

**Comment by STRd6** [comment]
Thanks, that's very useful! I was mainly looking at the project for
inspiration for a CoffeeScript successor I've been rolling around. :)
